// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/staking/v1beta1/shares.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SharesRepartition defines the asset staking repartition.
type SharesRepartition struct {
	Denom           string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	BaseWeight      uint64 `protobuf:"varint,3,opt,name=base_weight,json=baseWeight,proto3" json:"base_weight,omitempty"`
	// Total shares staked in the network
	NetworkShares                 cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=network_shares,json=networkShares,proto3,customtype=cosmossdk.io/math.Int" json:"network_shares"`
	NetworkPercentageSecurisation string                `protobuf:"bytes,5,opt,name=network_percentage_securisation,json=networkPercentageSecurisation,proto3" json:"network_percentage_securisation,omitempty"`
}

func (m *SharesRepartition) Reset()         { *m = SharesRepartition{} }
func (m *SharesRepartition) String() string { return proto.CompactTextString(m) }
func (*SharesRepartition) ProtoMessage()    {}
func (*SharesRepartition) Descriptor() ([]byte, []int) {
	return fileDescriptor_46ae8d12fcbf529f, []int{0}
}
func (m *SharesRepartition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SharesRepartition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SharesRepartition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SharesRepartition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharesRepartition.Merge(m, src)
}
func (m *SharesRepartition) XXX_Size() int {
	return m.Size()
}
func (m *SharesRepartition) XXX_DiscardUnknown() {
	xxx_messageInfo_SharesRepartition.DiscardUnknown(m)
}

var xxx_messageInfo_SharesRepartition proto.InternalMessageInfo

func (m *SharesRepartition) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *SharesRepartition) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *SharesRepartition) GetBaseWeight() uint64 {
	if m != nil {
		return m.BaseWeight
	}
	return 0
}

func (m *SharesRepartition) GetNetworkPercentageSecurisation() string {
	if m != nil {
		return m.NetworkPercentageSecurisation
	}
	return ""
}

func init() {
	proto.RegisterType((*SharesRepartition)(nil), "cosmos.staking.v1beta1.SharesRepartition")
}

func init() {
	proto.RegisterFile("cosmos/staking/v1beta1/shares.proto", fileDescriptor_46ae8d12fcbf529f)
}

var fileDescriptor_46ae8d12fcbf529f = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4e, 0xeb, 0x30,
	0x14, 0xc6, 0x93, 0xde, 0xf6, 0x4a, 0xd7, 0x57, 0xf7, 0x4f, 0xa3, 0xde, 0xab, 0x50, 0x89, 0xa4,
	0x02, 0x86, 0x22, 0x68, 0xa2, 0x8a, 0x8d, 0x8d, 0x0e, 0x95, 0xba, 0xa1, 0x74, 0x40, 0x62, 0x89,
	0x9c, 0xc4, 0x4a, 0xac, 0x28, 0x76, 0x64, 0x9f, 0x52, 0x78, 0x0b, 0x36, 0x56, 0x1e, 0x82, 0x87,
	0xe8, 0x58, 0x31, 0x21, 0x86, 0x0a, 0xb5, 0x0b, 0x8f, 0x81, 0x12, 0xbb, 0x15, 0x0b, 0x4b, 0x62,
	0x7f, 0xfe, 0x9d, 0xcf, 0xe7, 0x7c, 0x46, 0x87, 0x31, 0x97, 0x05, 0x97, 0xbe, 0x04, 0x9c, 0x53,
	0x96, 0xfa, 0x37, 0xc3, 0x88, 0x00, 0x1e, 0xfa, 0x32, 0xc3, 0x82, 0x48, 0xaf, 0x14, 0x1c, 0xb8,
	0xf5, 0x5f, 0x41, 0x9e, 0x86, 0x3c, 0x0d, 0x75, 0x3b, 0x29, 0x4f, 0x79, 0x8d, 0xf8, 0xd5, 0x4a,
	0xd1, 0xdd, 0xa3, 0xaf, 0x2c, 0x75, 0xb5, 0xa2, 0xf6, 0x14, 0x15, 0xaa, 0x72, 0x7d, 0x81, 0x3a,
	0x6a, 0xe3, 0x82, 0x32, 0xee, 0xd7, 0x5f, 0x25, 0x1d, 0x3c, 0x34, 0x50, 0x7b, 0x5a, 0xb7, 0x14,
	0x90, 0x12, 0x0b, 0xa0, 0x40, 0x39, 0xb3, 0x3a, 0xa8, 0x95, 0x10, 0xc6, 0x0b, 0xdb, 0xec, 0x99,
	0xfd, 0x1f, 0x81, 0xda, 0x58, 0xc7, 0xe8, 0x6f, 0xcc, 0x19, 0x08, 0x1c, 0x43, 0x88, 0x93, 0x44,
	0x10, 0x29, 0xed, 0x46, 0x0d, 0xfc, 0xd9, 0xea, 0x17, 0x4a, 0xb6, 0x5c, 0xf4, 0x33, 0xc2, 0x92,
	0x84, 0x73, 0x42, 0xd3, 0x0c, 0xec, 0x6f, 0x3d, 0xb3, 0xdf, 0x0c, 0x50, 0x25, 0x5d, 0xd5, 0x8a,
	0x15, 0xa0, 0xdf, 0x8c, 0xc0, 0x9c, 0x8b, 0x3c, 0x54, 0x89, 0xd8, 0xcd, 0xca, 0x69, 0x74, 0xb2,
	0x58, 0xb9, 0xc6, 0xeb, 0xca, 0xfd, 0xa7, 0x1a, 0x97, 0x49, 0xee, 0x51, 0xee, 0x17, 0x18, 0x32,
	0x6f, 0xc2, 0xe0, 0xf9, 0x69, 0x80, 0xf4, 0x44, 0x13, 0x06, 0xc1, 0x2f, 0x6d, 0xa1, 0x06, 0xb0,
	0xc6, 0xc8, 0xdd, 0x7a, 0x96, 0x44, 0xc4, 0x84, 0x01, 0x4e, 0x49, 0x28, 0x49, 0x3c, 0x13, 0x54,
	0xe2, 0x6a, 0x30, 0xbb, 0x55, 0xb7, 0xbb, 0xaf, 0xb1, 0xcb, 0x1d, 0x35, 0xfd, 0x04, 0x9d, 0x37,
	0xdf, 0x1f, 0x5d, 0x73, 0x34, 0x5e, 0xac, 0x1d, 0x73, 0xb9, 0x76, 0xcc, 0xb7, 0xb5, 0x63, 0xde,
	0x6f, 0x1c, 0x63, 0xb9, 0x71, 0x8c, 0x97, 0x8d, 0x63, 0x5c, 0x9f, 0xa6, 0x14, 0xb2, 0x59, 0xe4,
	0xc5, 0xbc, 0xd0, 0xf9, 0xea, 0xdf, 0x40, 0x26, 0xb9, 0x7f, 0xbb, 0x7b, 0x1f, 0xb8, 0x2b, 0x89,
	0x8c, 0xbe, 0xd7, 0x41, 0x9f, 0x7d, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x0a, 0xeb, 0x4a, 0x11,
	0x02, 0x00, 0x00,
}

func (this *SharesRepartition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SharesRepartition)
	if !ok {
		that2, ok := that.(SharesRepartition)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Denom != that1.Denom {
		return false
	}
	if this.ContractAddress != that1.ContractAddress {
		return false
	}
	if this.BaseWeight != that1.BaseWeight {
		return false
	}
	if !this.NetworkShares.Equal(that1.NetworkShares) {
		return false
	}
	if this.NetworkPercentageSecurisation != that1.NetworkPercentageSecurisation {
		return false
	}
	return true
}
func (m *SharesRepartition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SharesRepartition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SharesRepartition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NetworkPercentageSecurisation) > 0 {
		i -= len(m.NetworkPercentageSecurisation)
		copy(dAtA[i:], m.NetworkPercentageSecurisation)
		i = encodeVarintShares(dAtA, i, uint64(len(m.NetworkPercentageSecurisation)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.NetworkShares.Size()
		i -= size
		if _, err := m.NetworkShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintShares(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.BaseWeight != 0 {
		i = encodeVarintShares(dAtA, i, uint64(m.BaseWeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintShares(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintShares(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintShares(dAtA []byte, offset int, v uint64) int {
	offset -= sovShares(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SharesRepartition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovShares(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovShares(uint64(l))
	}
	if m.BaseWeight != 0 {
		n += 1 + sovShares(uint64(m.BaseWeight))
	}
	l = m.NetworkShares.Size()
	n += 1 + l + sovShares(uint64(l))
	l = len(m.NetworkPercentageSecurisation)
	if l > 0 {
		n += 1 + l + sovShares(uint64(l))
	}
	return n
}

func sovShares(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozShares(x uint64) (n int) {
	return sovShares(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SharesRepartition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShares
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SharesRepartition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SharesRepartition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseWeight", wireType)
			}
			m.BaseWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseWeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NetworkShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkPercentageSecurisation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShares
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShares
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShares
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkPercentageSecurisation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShares(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShares
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipShares(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowShares
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShares
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShares
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthShares
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupShares
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthShares
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthShares        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowShares          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupShares = fmt.Errorf("proto: unexpected end of group")
)
