// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/gov/v1beta1/execproposals.proto

package v1beta1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Un content legacy générique, modulable
type ModuleExecProposal struct {
	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// route du legacy handler (ex: "slashing", "staking", "bank", etc.)
	Route string `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	// une ou plusieurs sdk.Msg encodées en Any
	Messages []*types.Any `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (m *ModuleExecProposal) Reset()         { *m = ModuleExecProposal{} }
func (m *ModuleExecProposal) String() string { return proto.CompactTextString(m) }
func (*ModuleExecProposal) ProtoMessage()    {}
func (*ModuleExecProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_9acb1eb44f71a03f, []int{0}
}
func (m *ModuleExecProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ModuleExecProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ModuleExecProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ModuleExecProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleExecProposal.Merge(m, src)
}
func (m *ModuleExecProposal) XXX_Size() int {
	return m.Size()
}
func (m *ModuleExecProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleExecProposal.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleExecProposal proto.InternalMessageInfo

func (m *ModuleExecProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ModuleExecProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ModuleExecProposal) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *ModuleExecProposal) GetMessages() []*types.Any {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*ModuleExecProposal)(nil), "cosmos.gov.v1beta1.ModuleExecProposal")
}

func init() {
	proto.RegisterFile("cosmos/gov/v1beta1/execproposals.proto", fileDescriptor_9acb1eb44f71a03f)
}

var fileDescriptor_9acb1eb44f71a03f = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x3b, 0x7f, 0x7f, 0x45, 0xd3, 0xdd, 0x50, 0x30, 0xad, 0x30, 0x14, 0x17, 0xd2, 0x4d,
	0x67, 0xac, 0x3e, 0x81, 0x05, 0x37, 0x42, 0x41, 0xba, 0x74, 0x23, 0x49, 0x7a, 0x1d, 0x83, 0x69,
	0x6f, 0xc8, 0x9d, 0x94, 0xe4, 0x2d, 0x7c, 0x15, 0xc1, 0x87, 0x10, 0x57, 0x5d, 0xba, 0x94, 0xe4,
	0x45, 0xc4, 0x99, 0x89, 0xb8, 0x1a, 0xce, 0xcc, 0x77, 0xe6, 0x9e, 0x7b, 0x82, 0xf3, 0x04, 0x69,
	0x83, 0xa4, 0x34, 0xee, 0xd4, 0x6e, 0x1e, 0x83, 0x89, 0xe6, 0x0a, 0x2a, 0x48, 0xf2, 0x02, 0x73,
	0xa4, 0x28, 0x23, 0x99, 0x17, 0x68, 0x90, 0x73, 0xc7, 0x49, 0x8d, 0x3b, 0xe9, 0xb9, 0xf1, 0x48,
	0x23, 0xea, 0x0c, 0x94, 0x25, 0xe2, 0xf2, 0x51, 0x45, 0xdb, 0xda, 0xe1, 0xe3, 0x91, 0xc3, 0x1f,
	0xac, 0x52, 0xde, 0x6b, 0xc5, 0xd9, 0x2b, 0x0b, 0xf8, 0x12, 0xd7, 0x65, 0x06, 0x37, 0x15, 0x24,
	0x77, 0x7e, 0x0e, 0x1f, 0x06, 0x07, 0x26, 0x35, 0x19, 0x84, 0x6c, 0xc2, 0xa6, 0xc7, 0x2b, 0x27,
	0xf8, 0x24, 0x18, 0xac, 0x81, 0x92, 0x22, 0xcd, 0x4d, 0x8a, 0xdb, 0xf0, 0x9f, 0x7d, 0xfb, 0x7b,
	0xf5, 0xe3, 0x2b, 0xb0, 0x34, 0x10, 0xf6, 0x9d, 0xcf, 0x0a, 0xbe, 0x0c, 0x8e, 0x36, 0x40, 0x14,
	0x69, 0xa0, 0xf0, 0xff, 0xa4, 0x3f, 0x1d, 0x5c, 0x0e, 0xa5, 0x4b, 0x2b, 0xbb, 0xb4, 0xf2, 0x7a,
	0x5b, 0x2f, 0x4e, 0x3f, 0xde, 0x66, 0x27, 0x3e, 0x5e, 0x1c, 0x11, 0x74, 0xbb, 0xc9, 0x25, 0xe9,
	0xd5, 0xef, 0x17, 0x8b, 0xdb, 0xf7, 0x46, 0xb0, 0x7d, 0x23, 0xd8, 0x57, 0x23, 0xd8, 0x4b, 0x2b,
	0x7a, 0xfb, 0x56, 0xf4, 0x3e, 0x5b, 0xd1, 0xbb, 0xbf, 0xd0, 0xa9, 0x79, 0x2a, 0x63, 0x99, 0xe0,
	0xc6, 0xaf, 0xe9, 0x8f, 0x19, 0xad, 0x9f, 0x55, 0x65, 0x7b, 0x35, 0x75, 0x0e, 0xd4, 0xb5, 0x1b,
	0x1f, 0xda, 0x00, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xad, 0xea, 0xcb, 0x7b, 0x7a, 0x01,
	0x00, 0x00,
}

func (m *ModuleExecProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ModuleExecProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ModuleExecProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Messages) > 0 {
		for iNdEx := len(m.Messages) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Messages[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintExecproposals(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Route) > 0 {
		i -= len(m.Route)
		copy(dAtA[i:], m.Route)
		i = encodeVarintExecproposals(dAtA, i, uint64(len(m.Route)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintExecproposals(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintExecproposals(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintExecproposals(dAtA []byte, offset int, v uint64) int {
	offset -= sovExecproposals(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ModuleExecProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovExecproposals(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovExecproposals(uint64(l))
	}
	l = len(m.Route)
	if l > 0 {
		n += 1 + l + sovExecproposals(uint64(l))
	}
	if len(m.Messages) > 0 {
		for _, e := range m.Messages {
			l = e.Size()
			n += 1 + l + sovExecproposals(uint64(l))
		}
	}
	return n
}

func sovExecproposals(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozExecproposals(x uint64) (n int) {
	return sovExecproposals(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ModuleExecProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExecproposals
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ModuleExecProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ModuleExecProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecproposals
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExecproposals
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExecproposals
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecproposals
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExecproposals
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExecproposals
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Route", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecproposals
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExecproposals
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExecproposals
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Route = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecproposals
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExecproposals
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthExecproposals
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = append(m.Messages, &types.Any{})
			if err := m.Messages[len(m.Messages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExecproposals(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExecproposals
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExecproposals(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExecproposals
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExecproposals
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExecproposals
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExecproposals
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupExecproposals
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthExecproposals
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthExecproposals        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExecproposals          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupExecproposals = fmt.Errorf("proto: unexpected end of group")
)
